-- sys.exec("./examples/fps.lua")
-- sys.exec("./examples/static.lua")
-- sys.exec("./examples/sun.lua")
sys.exec("./examples/game_input.lua")
sys.exec("./examples/typist.lua")
sys.exec("./examples/showimage.lua")
-- sys.exec("./examples/piano.lua")
-- sys.exec("./examples/daisy.lua")
sys.exec("./examples/juggler.lua")
